#!/usr/bin/env python3
"""
Build AGENT_INDEX.md from the live tree.

Run on demand or via a session-start hook. The file is *overwritten*, not
appended to — agents reading it expect a current map, not a history.

Two-phase design:

1. Static skeleton (this file's CONTENT is the source of truth — keep AGENT_INDEX
   hand-curated for the prose).
2. This script regenerates the dynamic tables (counts, file lists) and writes
   the final file to disk.

Currently the skeleton IS the file. This script will grow to inject dynamic
content when needed (e.g., a "current wave" row, an "open PRs" row).

Usage:
    python scripts/build_agent_index.py           # write AGENT_INDEX.md
    python scripts/build_agent_index.py --check   # exit non-zero if drift

The --check mode is for CI / pre-commit: it fails the commit when the index
has gone stale relative to the tree it claims to index.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = PROJECT_ROOT / "AGENT_INDEX.md"


def _git(*args, timeout=10):
    """Always wrap git in a timeout. The harness hangs ~30% of invocations."""
    try:
        return subprocess.run(
            ["git", *args],
            capture_output=True, text=True,
            cwd=PROJECT_ROOT, timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return None


def _collect_dynamic_rows() -> list[str]:
    """Build the rows that go below the static skeleton.

    Today this is conservative: capture the count of .agent_contracts/
    contracts, the count of wiki pages, the local main SHA, and which remote
    is configured. Tomorrow it can grow.
    """
    rows: list[str] = []

    r = _git("rev-parse", "--short", "HEAD")
    head = r.stdout.strip() if r and r.returncode == 0 else "?"

    r = _git("for-each-ref", "--format=%(refname:short)", "refs/heads/")
    branches = r.stdout.splitlines() if r and r.returncode == 0 else []
    branches = [b for b in branches if b]

    r = _git("remote", "get-url", "origin")
    origin_url = r.stdout.strip() if r and r.returncode == 0 else "?"

    contracts = sorted((PROJECT_ROOT / ".agent_contracts").glob("*/spec.md")) \
        if (PROJECT_ROOT / ".agent_contracts").is_dir() else []

    wiki = sorted((PROJECT_ROOT / "wiki").rglob("*.md")) \
        if (PROJECT_ROOT / "wiki").is_dir() else []

    papers = sorted(p.name for p in (PROJECT_ROOT / "raw" / "papers").glob("*.md")) \
        if (PROJECT_ROOT / "raw" / "papers").is_dir() else []

    rows.append("## Live snapshot (regenerated by `scripts/build_agent_index.py`)")
    rows.append("")
    rows.append(f"- Local HEAD: `{head}`")
    rows.append(f"- `origin` URL: `{origin_url}`")
    rows.append(f"- Local branches: {len(branches)} (`git for-each-ref refs/heads/`)")
    rows.append(f"- `.agent_contracts/` specs: {len(contracts)}")
    rows.append(f"- `wiki/` markdown pages: {len(wiki)}")
    rows.append(f"- `raw/papers/*.md` tracked: {len(papers)}")
    rows.append("")

    if contracts:
        rows.append("### Specs on disk")
        rows.append("")
        for c in contracts:
            rel = c.relative_to(PROJECT_ROOT).parent
            rows.append(f"- `{rel}`")
        rows.append("")

    return rows


def _main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="Exit non-zero if AGENT_INDEX.md is out of date.")
    args = p.parse_args()

    # For now: AGENT_INDEX.md is hand-curated. The dynamic rows go above as a
    # banner the next implementer can choose to inline. Regenerating the whole
    # file from a template would risk losing human edits; until we have a
    # real templating layer, --check just verifies the file is non-stale by
    # file mtime (cheap heuristic) and reads the dynamic snapshot.
    dynamic_rows = _collect_dynamic_rows()
    snapshot = "\n".join(dynamic_rows)

    if args.check:
        # Print to stderr so it shows up in CI; verify existence only.
        if not INDEX_PATH.exists():
            print(f"FAIL: {INDEX_PATH} missing", file=sys.stderr)
            return 1
        # The freshness check compares file mtime to .agent_contracts/
        # newest spec mtime. If the spec changed after the index, drift.
        newest_spec_mtime = 0.0
        if (PROJECT_ROOT / ".agent_contracts").is_dir():
            for sp in (PROJECT_ROOT / ".agent_contracts").glob("*/spec.md"):
                newest_spec_mtime = max(newest_spec_mtime, sp.stat().st_mtime)
        idx_mtime = INDEX_PATH.stat().st_mtime
        if newest_spec_mtime > idx_mtime:
            print(
                f"DRIFT: AGENT_INDEX.md is older than a spec it indexes.\n"
                f"  spec newest mtime: {newest_spec_mtime:.0f}\n"
                f"  index mtime:        {idx_mtime:.0f}\n"
                f"Run: python scripts/build_agent_index.py",
                file=sys.stderr,
            )
            return 1
        print(snapshot)
        return 0

    # Write mode: append the snapshot banner to the existing human-curated
    # file by re-writing it. For now the file stays hand-edited; the banner
    # is the only generated region.
    existing = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
    if "## Live snapshot" in existing:
        head, _, _ = existing.partition("\n## Live snapshot")
        body = head.rstrip() + "\n\n" + snapshot
    else:
        body = existing.rstrip() + "\n\n" + snapshot
    INDEX_PATH.write_text(body, encoding="utf-8")
    print(f"wrote {INDEX_PATH} ({len(body)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(_main())
